export const menuTableEntradas = document.getElementById('menu-table-entradas')
export const menuTableSopas = document.getElementById('menu-table-sopas')
export const menuTableCriollo = document.getElementById('menu-table-criollo')
export const menuTablePostres = document.getElementById('menu-table-postres')
export const menuTableBebidas = document.getElementById('menu-table-bebidas')

export const menuCardEntradas = document.getElementById('menu-card-entradas')
export const menuCardSopas = document.getElementById('menu-card-sopas')
export const menuCardCriollo = document.getElementById('menu-card-criollo')
export const menuCardPostres = document.getElementById('menu-card-postres')
export const menuCardBebidas = document.getElementById('menu-card-bebidas')
